version: 2

project_name: tmx

before:
  hooks:
    - go mod tidy

builds:
  - main: ./
    binary: tmx
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/vbrdnk/tmx/cmd.Version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Signing with cosign (keyless, uses GitHub Actions OIDC)
signs:
  - cmd: cosign
    artifacts: checksum
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

homebrew_casks:
  - name: tmx
    binaries:
      - tmx
    homepage: "https://github.com/vbrdnk/tmx"
    description: "A tmux session manager with fzf integration"
    dependencies:
      - formula: tmux
      - formula: fzf
    caveats: |
      tmx requires tmux and fzf (installed as dependencies).
      For enhanced functionality, optionally install fd and zoxide:
        brew install fd zoxide
    repository:
      owner: vbrdnk
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    # commit_author:
    #   name: goreleaserbot
    #   email: bot@goreleaser.com
    # commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"

# Release configuration
release:
  # GitHub release
  github:
    owner: vbrdnk
    name: tmx

  # Release notes
  header: |
    ## tmx {{ .Version }}

    Welcome to this new release of tmx! 🎉

    **Full changelog**: https://github.com/vbrdnk/tmx/compare/{{ .PreviousTag }}...{{ .Tag }}

  footer: |
    ## Installation

    ### Homebrew (macOS/Linux)
    ```bash
    brew install vbrdnk/tap/tmx
    ```

    ### Direct Download
    Download the appropriate binary for your platform from the assets above.

    ### Go Install
    ```bash
    go install github.com/vbrdnk/tmx@latest
    ```

    **Thanks to all contributors! 🙏**

# Metadata
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
